### ISSUE TITLE
D-Link 932L live streaming

### ISSUE THREAD

**Issue by acharris76** [KhaosT/homebridge-camera-ffmpeg#132]
Was wondering whether anyone has been able to get a live stream from a D-Link 932L to appear in Homekit via Homebridge and if they did what plugin and configuration they were using.
I have managed to get a still shot to appear in Homekit which updates automatically every 10 seconds but no live stream.
Thanks

**Comment by linusnyren** [comment]
I got the 932L to and only getting stills aswell.
What does your config look like?

here´s mine;
{
      "platform" : "Camera-ffmpeg",
      "cameras" : [
        {
          "name" : "Kameran",
          "videoConfig" : {
            "vcodec" : "h264_omx",
            "source" : "-re -f mjpg -i http://admin:pw@192.168.1.90/video/mjpg.cgi",
            "maxFPS" : 20,
            "maxHeight" : 480,
            "maxStreams" : 2,
            "maxWidth" : 640,
            "stillImageSource" : "-f mjpeg -i http://admin:pw@192.168.1.90/video/mjpg.cgi"
          }
        }
      ]
    }

And when i try to stream to the homekit app i get this commandline in hombridge

-re -f mjpg -i http://admin:Susanna1@192.168.1.90/video/mjpg.cgi -threads 0 -vcodec h264_omx -an -pix_fmt yuv420p -r 30 -f rawvideo -tune zerolatency -vf scale=640:360 -b:v 132k -bufsize 132k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params RJb9MeBchB7xiJ/0HdKHbKQG+7r81C9+vXJs7+AY srtp://192.168.1.98:52785?rtcpport=52785&localrtcpport=52785&pkt_size=1378

i bought the d-link 932l only cause it was in the wiki instructions and seemed easy to get setup, i was totally wrong.

Could someone please assist us in this?

**Comment by linusnyren** [comment]
i can create a mp4 file with this cmd
ffmpeg -re -i http://admin:pw@192.168.1.90/video/mjpg.cgi -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 15 testing.mp4

so i know the stream works, how do i configure homebridge to stream that?
please help a noob out!

**Comment by kodibrain** [comment]
Hi,
I use a DLink 932L. My configuration works!

{
          "name" : "camera",
          "videoConfig" : {
            "maxHeight" : 480,
            "maxStreams" : 2,
            "source" : "-re -i http://admin:pw@192.168.2.1/video/mjpg.cgi",
            "maxWidth" : 640,
            "stillImageSource" : "-i http://admin:pw@192.168.2.1/video/mjpg.cgi",
            "maxFPS" : 10
          }
}

**Comment by linusnyren** [comment]
Thank you so much! that actually fixed it, must have been that my fps was set to 15 earlier

**Comment by kodibrain** [comment]
nope, but the videoconnection is works for me enough.

**Comment by jeffl78** [comment]
Hi,
I have a 932L with hardware version B is running on a fairly up to date raspi3b and I recently got still function to work after changing just about every part of the config possiable.  The challenge I am facing now is the video stream still will not work.  I have a few questions, the first is if anyone has been adjusting settings like the resolution and frame rate in the mydlink to mach what they are set to in the config.json file.  My background is in biology, medicine and lab science but am learning more about coding since I got a pi last year so port forwarding is a bit new to me.  Can someone please confirm that it is the ip address of the camera that is entered into the router vs the raspberry pi.  Lastly, i notced that if I open the camera in flame the ip address assigned now matches the static address of my pi and prior to port forwarding flame should the ip address assigned to the camera was the same as the address shown in mydlink for the camera.  Adding to this is the fact that flame shows 2 port numbers for the camera, one assigned for the pi and one for the camera, however mydlink shows a different port, port 80 in my case, which is the port I currently have forwarded in my router using the ip address mydlink reports for the camera.  Is the port and ip address reported by mydlink the correct criteria to use?  Any information related to this plugin and related concepts whatsoever is more then welcome.  Below is a error code homebridge is giving and my current config.json file.  I should mention that I have changed the portion of the stream address that shows a port number to video and back again with no change in the still frame feature and still no video stream in homekit.



Homebridge says the following when the video is pressed in homebridge:

[2018-3-11 20:19:42] [Camera-ffmpeg] Start streaming video from KittyKam6 with 640x360@132kBit
[2018-3-11 20:19:42] [Camera-ffmpeg] ERROR: FFmpeg exited with code 1



},
  "platforms" : [
    {
      "cameras" : [
        {
          "name" : "KittyKam6",
          "videoConfig" : {
            "maxHeight" : "480",
            "maxStreams" : "
            "source" : "-re -i http://admin:Poop1967@192.168.0.101:video/mjpg.cgi",
            "maxWidth" : "680",
            "stillImageSource" : "-re -i http://admin:Poop1967@192.168.0.101:video/mjpg.cgi
            "maxFPS" : "10"
          }
        }
      ],
      "name" : "",
      "platform" : "Camera-ffmpeg"
