### ISSUE TITLE
Working solution for any Belkin NetCam

### ISSUE THREAD

**Issue by 350d** [KhaosT/homebridge-camera-ffmpeg#138]
Hello! I have a solution to support for any `Belkin Netcam` via `camera-ffmpeg` plugin.
I have `NetCam HD+` model `F7D7606v1` and this model doesn't have any local broadcast endpoints (only in setup mode local stream available, but camera create open wifi network in this mode). Belkin disabled it via firmware update some time ago.
I'm not a `node.js` guy, so, I'm looking for someone who can refactor my code in proper way. The Idea is just to take session from Belkin web interface and pass it to ffmpeg. Here is the prototype and it works just fine for me:
````
FFMPEG.prototype.updateBelkinNetcamSession = function(ffmpegOpt, callback) {
      var request = require('request');
      request = request.defaults({
          jar: true
      });
      var j = request.jar();
      var loginurl = 'https://netcam.belkin.com/app/c/login.html';
      var authurl = 'https://netcam.belkin.com/cxs/api/auth/login';
      var netcamheaders = {
          AntiCSRF: 'AntiCSRF',
          Host: 'netcam.belkin.com',
          Origin: 'https://netcam.belkin.com',
          Referer: loginurl,
          'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36'
      };

      request({
          url: loginurl,
          jar: j
      }, function(error, response, body) {
          request.post({
                  url: authurl,
                  json: {
                      password: ffmpegOpt.netcam.password,
                      username: ffmpegOpt.netcam.login
                  },
                  headers: netcamheaders,
                  jar: j
              },
              function(error, response, body) {
                  j.getCookies(authurl).forEach(function(cookie) {
                      if (cookie.key == 'SeedonkSession') {
                          var cameraurl = 'https://netcam.belkin.com/cxs/api/devices/' + ffmpegOpt.netcam.cameraid + '/cam/liveStream?viewerSessionId=' + cookie.value;
                          ffmpegOpt.source = '-headers Cookie:SeedonkSession=' + cookie.value + '; -i ' + cameraurl;
                          ffmpegOpt.stillImageSource = '-headers Cookie:SeedonkSession=' + cookie.value + '; -skip_frame nokey -i ' + cameraurl + ' -vframes 1 -r 1';
                          request({
                              url: 'https://netcam.belkin.com/cxs/api/services/forDevice/' + ffmpegOpt.netcam.cameraid + '/statusFull',
                              jar: j
                          }, function() {

                              request.post({
                                  headers: netcamheaders,
                                  json: {
                                      keepaliveSec: 3600
                                  },
                                  url: 'https://netcam.belkin.com/cxs/api/devices/' + ffmpegOpt.netcam.cameraid + '/cam/do/createViewerSession',
                                  jar: j
                              }, function(error, response, body) {
                                console.log(body.viewerSessionId);
                                callback(ffmpegOpt);
                                // TO DO:
                                // DEVICES: GET https://netcam.belkin.com/cxs/api/devices?includeDeleted=true
                                // KEEP ALIVE: POST https://netcam.belkin.com/cxs/api/keepalive/{viewerSessionId}
                              });
                          });
                      };
                  });

                  if (!error && response.statusCode == 200) {
                      //console.log(response);
                  }
              }
          );
      });
}
````

Additionally `FFMPEG.prototype.handleStreamRequest` updated with:
````
       if (this.ffmpegOpt.netcam) {

          let self = this;
          this.updateBelkinNetcamSession(this.ffmpegOpt, function(ffmpegOpt) {
            //console.log(ffmpegOpt);
            let ffmpegCommand = ffmpegOpt.source + ' -threads 0 -vcodec '+vcodec+' -an -pix_fmt yuv420p -r '+
            fps +' -f rawvideo -vf scale='+ width +':'+ height +' -b:v '+ bitrate +'k -bufsize '+
             bitrate +'k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params '+
             videoKey.toString('base64')+' srtp://'+targetAddress+':'+targetVideoPort+'?rtcpport='+targetVideoPort+
             '&localrtcpport='+targetVideoPort+'&pkt_size=1378';
            console.log(ffmpegCommand);
            let ffmpeg = spawn('ffmpeg', ffmpegCommand.split(' '), {env: process.env});
            self.ongoingSessions[sessionIdentifier] = ffmpeg;

            delete self.pendingSessions[sessionIdentifier];
          });
       } else {
          let ffmpegCommand = this.ffmpegSource + ' -threads 0 -vcodec '+vcodec+' -an -pix_fmt yuv420p -r '+
          fps +' -f rawvideo -vf scale='+ width +':'+ height +' -b:v '+ bitrate +'k -bufsize '+
           bitrate +'k -payload_type 99 -ssrc 1 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params '+
           videoKey.toString('base64')+' srtp://'+targetAddress+':'+targetVideoPort+'?rtcpport='+targetVideoPort+
           '&localrtcpport='+targetVideoPort+'&pkt_size=1378';
          console.log(ffmpegCommand);
          let ffmpeg = spawn('ffmpeg', ffmpegCommand.split(' '), {env: process.env});
          this.ongoingSessions[sessionIdentifier] = ffmpeg;

          delete this.pendingSessions[sessionIdentifier];
       }
      }
````

and

somewhere inside main FFMPEG function after:
````
  if (!ffmpegOpt.source) {
    throw new Error("Missing source for camera.");
  }
````
I have this line:
````
this.ffmpegOpt = ffmpegOpt;
````

`config.json`:
````
                  "name": "testcam",
                  "videoConfig": {
                      "source": "x",
                      "stillImageSource": "x",
                      "maxStreams": 2,
                      "maxWidth": 1280,
                      "maxHeight": 720,
                      "maxFPS": 30,
                      "vcodec": "h264_omx",
                      "netcam": {
                        "login": "yourlogin",
                        "password": "yourpassword",
                        "cameraid": yourcameraid
                      }
                  }
                }
````

So, `handleSnapshotRequest` should be updated too.
Optimization - No need to recreate session on every camera open, we can just ping this session time to time like Belkin website.

**Comment by DMBlakeley** [comment]
I do like this approach as the Netcams are used as designed rather than putting in setup mode.  I have added your above changes to my local files.  I am able to add the Netcam to HomeKit, however, when I access the Live stream I receive a message that the camera is not available.  I have confirmed that the camera is accessible via a web browser (Google Chrome) and that it is available in the iPhone app.

Any troubleshooting tips or suggestions that you can provide.

**Comment by DMBlakeley** [comment]
I have 2 NetcamHDs, a V1 and a V2.  I have managed to establish a live video stream from both by:

- Update ffmeg.js with your changes from above
- Update ffmeg.js with the v0.1.1, v0.1.2, and 0.1.3 changes to handle multiple video cameras
- Change the vcodec from h264_omx to libx264

With these changes a couple of observations.  

- I was never able to get the V2 camera to work using the "setup" methodology even if this were the only camera so your web stream implementation is a big step forward.
- It takes 20+ seconds to establish a live stream.  Any ideas on how to improve?
- The live stream seems to time out but I do note in your comments that "keep alive" has not been implemented.

I am also not a node.js guy but I am not sure if required.

**Comment by 350d** [comment]
@DMBlakeley Hello! I think that session should be created once on first HomeBridge start or reload and after that plugin can just update it via `keepalive` endpoint and recreate it if needed. Looks like 20 seconds only needed for camera `cold start`. After that you can get image faster a bit. Livestream from outside of your HomeBridge network can be established only if you have home hub like iPad or Apple TV 4th gen or better.

**Comment by DMBlakeley** [comment]
I am basically a bit stumped with remote access.  I do have an Apple TV 4th gen (as well as a 4k version) as hubs in the house.  All other functions (lights, thermostat, security) work remotely without issue.  I also have a number of Automations based on time of day and whether home or not working without issue.  So, I don't understand why I get a "No Respond, This camera is not responding." message when away from the house.

My understanding is:
- When home, the iPhone sends video request to Homebridge -> request to netcam.belkin.com, -> video back to Mac Mini -> video to iPhone.
- When away, the iPhone sends video request to the Apple TV -> Homebridge -> netcam.belkin.com -> video back to Mac Mini -> video to Apple TV -> video the iPhone.

So, basic difference is that the Apple TV is in the loop for remote access.  I have Homebridge running on a Mac Mini.  Looking at the homebridge.log file I find that there is a request to connect to the camera when on the local wifi network but this is not the case when on LTE.  (I added a line in ffmeg.js to log the requests.)

Wondering if a port needs to be opened on the router to allow the video to stream out via LTE rather than locally on wifi.

**Comment by LumpyPoopie** [comment]
This looks promising to get my Netcam V2 cameras up and running on Homekit.  I need a little newbie advice on the code above. Where, exactly, do I enter the "FFMPEG.prototype.updateBelkinNetcamSession" and the "FFMPEG.prototype.handleStreamRequest" code? It's not obvious to me; Homebridge has been my introduction to linux.

Thank you all for helping me with this!

**Comment by LumpyPoopie** [comment]
I've figured out a few things, but also have some questions.
How can I find the "source" to put into the config.json file?  Currently, I'm pinging a local IP (-re -i http://admin:admin@10.0.1.44/goform/video), but I don't think that's right. I can't seem to find the non-local ip address of the camera.

Also, no snapshots are appearing on Homekit.  What is meant by "handleSnapshotRequest should be updated too"?

Finally, I found ffmpeg.js (v 0.1.3), and updated it with the code above.  I seem to be getting a few errors surrounding the code insert into "FFMPEG.prototype.handleStreamRequest".  Whenever I attempt to initiate a stream, I get errors such as below. Where should the additional block of code be insert?

-re -i http://admin:admin@10.0.1.44/goform/video -threads 0 -vcodec libx264 -an -pix_fmt yuv420p -r 15 -f rawvideo -tune zerolatency -vf scale=1280:720 -b:v 299k -bufsize 299k -payload_type 99 -ssrc 9322078 -f rtp -srtp_out_suite AES_CM_128_HMAC_SHA1_80 -srtp_out_params P+wSKQDegbUSQAKNB4vRpdvpdKSlPDzqK5uPx3UP srtp://10.0.1.37:58772?rtcpport=58772&localrtcpport=58772&pkt_size=1378
undefined
/usr/local/lib/node_modules/homebridge-camera-ffmpeg/ffmpeg.js:288
             videoKey.toString('base64')+' srtp://'+targetAddress+':'+targetVideoPort+'?rtcpport='+targetVideoPort+
             ^

ReferenceError: videoKey is not defined
    at /usr/local/lib/node_modules/homebridge-camera-ffmpeg/ffmpeg.js:288:14
    at Request._callback (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/ffmpeg.js:379:33)
    at Request.self.callback (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/request/request.js:186:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/request/request.js:1163:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/homebridge-camera-ffmpeg/node_modules/request/request.js:1085:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by 350d** [comment]
Here is my `ffmpeg.js`:
[ffmpeg.txt](https://github.com/KhaosT/homebridge-camera-ffmpeg/files/1755384/ffmpeg.txt)

**Comment by LumpyPoopie** [comment]
Thanks! that cleared up a few things!

I'm still not getting any snapshots or video.  I suspect I've got something awry in the                       "source" and "stillImageSource" sections of my config.json file.

"source":  "-re -i http://USERNAME:PASSWORD@10.0.1.44/goform/video"

**Comment by 350d** [comment]
Sources should be empty.

**Comment by LumpyPoopie** [comment]
What about the "cameraid": yourcameraid
Is "yourcameraid" the name I gave the camera in the NetCam app?

**Comment by DMBlakeley** [comment]
I can answer this one.   Go to netcam.belkin.com, log in and select the camera to view.  The cameraid is the number at the end of the html address.

**Comment by DMBlakeley** [comment]
Thanks so much for posting your ffmeg.js file.  Good to compare to mine to make sure that my interpretation of your post was correct.

I have spent more time trying to understand access to the cameras over cellular  as well as slow response.  

Cellular now works although I have made to no changes.  Suspect this is due to installation of tvOS 11.2.6 on my Apple TVs. When on local wifi, the targetAddress for the stream is my iPhone.  When on cellular, the targetAddress for the stream is the Apple TV.  Both as expected.

Slow access is interesting.  As I have 2 cameras I needed to implement the changes to ffmpeg.js for creating a unique ssrc for each stream request.  I found that if the ssrc is <256 then first access is reasonable although updates are still ~10 seconds apart.  Larger ssrc numbers seem to slow access down significantly.  Just an observation at this point.

**Comment by DMBlakeley** [comment]
I have been using WrapAPI to look at the commands that are being sent when viewing the Netcams via the netcam.belkin.com webpage.  I have observed that the SeedonkSession value is being used as the viewSessionId rather than the viewerSessionId which returned from createViewerSession call.  May explain why it seems to take so long to bring up the live video stream in the Home app.

**Comment by scottsimon1979** [comment]
Is anyone still active here?  I'm dying to get my two NetCamHD's working with HomeKit/homebridge.  I am stuggling to find where the ffmpeg.js file is located in my installation; I am running Homebridge and FFMPEG on a Mac.  Is anyone willing to help a guy out? :)

**Comment by DMBlakeley** [comment]
I have spent quite a bit of time tweaking the code poste by Vladimir to address the issues that I have posted.  I have also updated ffmpeg to include most of the recent posted updates to FFMPEG.  The problem that I continue to struggle with is that the implementation can be no quicker to respond than using the webpage interface to the Netcam cameras (netcam.belkin.com).  Getting started always takes at least 20 seconds and then I only get about 10 seconds of video before the stream stops (have not implemented the keep-alive function).  I have also found that the NetCamHD+ responds better than the NetCamHD versions of the camera.

**Comment by yyunikov** [comment]
@DMBlakeley could you post your code with instructions how to run it? Maybe some open source repo?

**Comment by felsmann** [comment]
> I am basically a bit stumped with remote access. I do have an Apple TV 4th gen (as well as a 4k version) as hubs in the house. All other functions (lights, thermostat, security) work remotely without issue. I also have a number of Automations based on time of day and whether home or not working without issue. So, I don't understand why I get a "No Respond, This camera is not responding." message when away from the house.
> 
> My understanding is:
> 
> * When home, the iPhone sends video request to Homebridge -> request to netcam.belkin.com, -> video back to Mac Mini -> video to iPhone.
> * When away, the iPhone sends video request to the Apple TV -> Homebridge -> netcam.belkin.com -> video back to Mac Mini -> video to Apple TV -> video the iPhone.
> 
> So, basic difference is that the Apple TV is in the loop for remote access. I have Homebridge running on a Mac Mini. Looking at the homebridge.log file I find that there is a request to connect to the camera when on the local wifi network but this is not the case when on LTE. (I added a line in ffmeg.js to log the requests.)
> 
> An interesting observation is that I do see snapshot requests in the log when over LTE, however, snapshots have not been implemented yet.
> 
> Wondering if a port needs to be opened on the router to allow the video to stream out via LTE rather than locally on wifi.

Hey did you ever figure out how to make it work at home?

**Comment by DMBlakeley** [comment]
I have the Netcams working both in the house as well as remotely.  Spent a lot of time trying to figure out how to improve the initial display of the video stream but came to the conclusion that the delay is on the Belkin side as initial display via the webpage is just as slow.

Currently working on updating the code to ffmpeg vs 0.1.8 as well as ensuring that it is working with iOS 12.1.1 and MacOS 10.14.2 as this brought HomeKit to the Mac.  Video streaming starts and displays for about 10 seconds so need to understand how to implement keep alive.  Also looking at getting the snapshots to work.  I'm not a professional coder so this is taking some time.

Wish there was a good choice for a HomeKit compatible camera as I believe that the Belkin Netcams will always have limitations. Now just an interesting project.

**Comment by dbowman68** [comment]
Hi, I have 5 Belkin NetCam F7D7601v1 since many years ago, always using the app on iOS (now 12.2) and running latest app versión 3.0.3 (from 2 years!). I don't know since when the app stopped working (I couldn't log in, however, I could log in with same credentials on netcam.belkin) Reading this topic, I guess is time to drop the iOS app, and try to configure another free video monitor app to run the NetCam on it, previous configuration on them. Could someone please write in a few lines the steps to accomplish this goal? I have some experience programming with old languages, I guess I can do something to solve my issue with the right guide. By the way, I contacted Belkin and I received an automated answer saying they will consider the issue for further releases (?). Thanks in advance for your time!

**Comment by DMBlakeley** [comment]
I have a Netcam v1 and v2 camera with iOS 12.3.1 and version 3.0.3 of the Netcam app and have no issues. I would suggest that you update your iOS to the latest, delete the Netcam app, reinstall the Netcam app, and sign in as a first step.

Several months ago I did have problems with updating the camera firmware and at the time I created a new Belkin account and reconnected the cameras. If update and reinstall did not work then I would try as a second step.

**Comment by dbowman68** [comment]
Thanks DMBlakeley, I'll follow your suggestion and I’ll let you know! Anyway, did you find a way to load the NetCam video in multiview software like mEye, iDMSS Lite, zMeye, zmNinja, or something similar? Belkin app works fine (just fine) but the limitation to watch one camera per time is really unbelievable..

**Comment by DMBlakeley** [comment]
No, I have not tried multiview software.  I am not sure that the Belkin Netcam would be compatible since they generate a video stream on demand via the app or web page. They will generate a video stream if you leave them cameras in “setup” mode. 

I tried using the solution posted at https://github.com/rudders/homebridge-platform-wemo/issues/58#issuecomment-324506210, however, I could not get more than 1 camera to work at a time. This approach disables the Netcam app as well as web access.

I am currently using an adaption of the solution which started this post which allows me to access through the Home app and retain access through the Netcam app. Access is a bit slow (same as Netcam app) and only displays about 20 seconds of live video after connecting.

You have quite an investment in 5 Belkin cameras so can understand that you are looking for a better software solution.

**Comment by dbowman68** [comment]
Thanks DM! I read very quickly the wemo#58 thread, and I have a question: the limitation for multiple using the method in your case was that you have v1 and v2 devices? In another hand, when you talk about iOS, you are not including iPhone or iPad device, isn’t it? I'm figuring the way to install FFMPEG and the others configuration without a kind of jailbreak. At last, a silly question, which method did you use to obtain the device internal IP address? I download the assigned IP table from the router, is very difficult to identify them because are not labeled, my idea is to fix the assignment directly in the router. Thanks in advance!

**Comment by DMBlakeley** [comment]
In my debugging I found that the thread #58 method only worked with v1 cameras. I could never get it to work on the v2 cameras. FFMPEG is installed on a Homebridge compatible device. In my case I am using a Mac Mini for Homebridge. With Homebridge installed and operational, devices handled by Homebridge appear in the Home app on an iPhone or iPad. Jail breaking is not necessary.

For the Netcam cameras I did fix/assign the IP address via the router configuration.  I used the “Net Analyzer” app on my iPhone to determine which IPs were assigned to the cameras and then assigned these via the router configuration.

If you do get your cameras operational and visible in the Home app there is the “HomeCam for HomeKit” which provides a pretty nice multiview display of all of your cameras. I have not tried it as I did not get more than 1 camera operational but I have purchases other apps by this developer and they delivered what was promised.

**Comment by dbowman68** [comment]
Thanks for your time DM, I'm beginning to understand the whole picture, thanks for your explanation. I'm a PC user, but I´ll try to install FFMPEG and Homebridge on a Mac (my daughter has one)

For IP address discovery, I’ll use some software I have already installed on PC. I’ll let you know thanks again!

**Comment by DMBlakeley** [comment]
You can install Homebridge on a PC, reference https://github.com/nfarina/homebridge/wiki/Install-HomeBridge-on-Windows-10-(new).

Whether you install on Windows or MacOS the unit needs to be located in your house and always powered. 

Good luck!

**Comment by dbowman68** [comment]
Thanks DM! I'll try in Windows first, I'll let you know. Thanks for your guide!

**Comment by dbowman68** [comment]
Well, small moves for me, after switching NetCam to config mode, I have a video on a web browser (HTTP://<ip>/goform/video

Besides this useful thread, I read something about this paper

https://aliteke.files.wordpress.com/2015/07/mobipstcmrrdy.pdf

and confirm the fact that they found some vulnerabilities on NetCam. As a first step I tried to log in Admin Page (in other forums I found ip/homeorg.asp or ip/home.asp) but I couldn't. In order to change admin/admin pwd, I tried to connect via Telnet (the NetCam runs a kind of Linux), and the connection was refused. I made a port scan, only found 80 opened (always in setup mode). 

As you can check, this situation differs from the document that I sent. Do you know if Belkin could change some of these parameters across the different versions? Do you find the way to enter in admin page with actual FW 2.4.8.5 version? Thanks in advance!

**Comment by DMBlakeley** [comment]
Thanks for passing on the article. You have already dug in deeper than I had with operating the camera in setup mode. Thinking back, one of the reasons I abandoned this mode is that if the streaming were to disconnect from my router there was no way to auto-reconnect it. You needed to unplug the camera for a reset, plug back in, and reconnect. Quite inconvenient when you are not at home.

Will be interested to see what you learn and find that you have stable operation.

Regards, Doug

**Comment by 350d** [comment]
@DMBlakeley Keep in mind that anyone can connect to your camera in setup mode. This is 100% insecure mode.

**Comment by DMBlakeley** [comment]
Understand. I am back to the standard mode using an adaptation of your post that started this stream.

**Comment by elesueur** [comment]
@DMBlakeley I too am trying to get my v2 camera working with homebridge. I am at the point where ffmpeg can connect to the netcam server and it seems to receive data, but the stream is never displayed on the iphone... I tried just running ffmpg on the command line and connecting to the srtp stream with VLC from my mac, and it seems to connect, but also doesn't display the video stream :( is everything still working for you? I am using iOS 12.4 and a variation of the code that was posted above.

**Comment by dbowman68** [comment]
Hi! Thanks for your update! Honestly, I decided to avoid losing time with a discontinued product, I had my five-minutes-professional-ego trying to solve this issue, searching a good configuration, but it would be more simple, we are talking about a camera device, as simple as that. So, I’m getting a quotation for Dahua cam or something similar device, with a lot of Apps designed to work on iOS. As you can imagine, it was not an easy decision, because I have 4 NetCam, but I decided to move forward. I’ll let you know about Dahua cam when I have and install them! Thanks!

 

 

De: elesueur <notifications@github.com> 
Enviado el: miércoles, 14 de agosto de 2019 17:38
Para: KhaosT/homebridge-camera-ffmpeg <homebridge-camera-ffmpeg@noreply.github.com>
CC: dbowman68 <dbowman@netchao.net>; Comment <comment@noreply.github.com>
Asunto: Re: [KhaosT/homebridge-camera-ffmpeg] Working solution for any Belkin NetCam (#138)

 

 <https://github.com/DMBlakeley> @DMBlakeley I too am trying to get my v2 camera working with homebridge. I am at the point where ffmpeg can connect to the netcam server and it seems to receive data, but the stream is never displayed on the iphone... I tried just running ffmpg on the command line and connecting to the srtp stream with VLC from my mac, and it seems to connect, but also doesn't display the video stream :( is everything still working for you? I am using iOS 12.4 and a variation of the code that was posted above.

**Comment by DMBlakeley** [comment]
I continue to use a variant of the configuration proposed at the start of this discussion stream. This provides basic functionality and I can also fall back to the iOS Netcam app if need be. Agree that the Netcam are pretty much deadline and watching developments in Homekit compatible cameras. Waiting to see what comes out with the HomeKit camera improvements via iOS13 before making the move.

**Comment by rcoletti116** [comment]
> I continue to use a variant of the configuration proposed at the start of this discussion stream. This provides basic functionality and I can also fall back to the iOS Netcam app if need be. Agree that the Netcam are pretty much deadline and watching developments in Homekit compatible cameras. Waiting to see what comes out with the HomeKit camera improvements via iOS13 before making the move.

@DMBlakeley Are you still using this? Do you mind sharing your copy of ffmpeg.js and the config.json snippet? I have this set up, but not working. A quick compare to yours might help me out. Thanks!

**Comment by DMBlakeley** [comment]
@rcoletti116 No, I recently refreshed my homebridge setup and did not carry over the Netcams. It was still working but I had added a Logitech Circle camera which works much better with HomeKit. Belkin recently announced EOL for the Netcams (https://www.belkin.com/us/support-article?articleNum=316642) so my version of the plugin would have stopped working on May 29th.

**Comment by rcoletti116** [comment]
woah! I had no idea my cameras are about to be bricked.

**Comment by DMBlakeley** [comment]
Yes, and rather short notice! I received the email on April 28, basically 30 days notice.

I ordered a couple of the new Eufy 2k cameras with HomeKit compatibiity on preorder for a pretty reasonable price as replacements. Have not received yet but you may want to check out for yourself.
