### ISSUE TITLE
connecting a pi-camera v2.1

### ISSUE THREAD

**Issue by cflurin** [KhaosT/homebridge-camera-ffmpeg#22]
I'm running homebridge-camera-ffmpeg on a Rpi 3.

The best solution I've found so far is `Point-to point streaming` (https://trac.ffmpeg.org/wiki/StreamingGuide):

```sh
raspivid -n -w 480 -h 320 -b 300000 -fps 15 -t 0 -o - | ffmpeg -i - -f mpegts udp://192.168.0.34:8090
```
note: 192.168.0.34 is the Rpi IP.

raspivid captures the video and sends the data through the pipe to ffmpeg.

```sh
pi@rpi4:~ $ raspivid -n -w 480 -h 320 -b 300000 -fps 15 -t 0 -o - | ffmpeg -i - -f mpegts udp://192.168.0.34:8090ffmpeg
  version N-82436-g0613627 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 4.9.2 (Raspbian 4.9.2-10)
  configuration: --arch=armel --target-os=linux --enable-gpl --enable-libx264 --enable-nonfree
  libavutil      55. 40.100 / 55. 40.100
  libavcodec     57. 66.103 / 57. 66.103
  libavformat    57. 57.100 / 57. 57.100
  libavdevice    57.  2.100 / 57.  2.100
  libavfilter     6. 67.100 /  6. 67.100
  libswscale      4.  3.101 /  4.  3.101
  libswresample   2.  4.100 /  2.  4.100
  libpostproc    54.  2.100 / 54.  2.100
Input #0, h264, from 'pipe:':
  Duration: N/A, bitrate: N/A
    Stream #0:0: Video: h264 (High), yuv420p(progressive), 480x320, 25 fps, 25 tbr, 1200k tbn, 50 tbc
Output #0, mpegts, to 'udp://192.168.0.34:8090':
  Metadata:
    encoder         : Lavf57.57.100
    Stream #0:0: Video: mpeg2video (Main), yuv420p, 480x320, q=2-31, 200 kb/s, 25 fps, 90k tbn, 25 tbc
    Metadata:
      encoder         : Lavc57.66.103 mpeg2video
    Side data:
      cpb: bitrate max/min/avg: 0/0/200000 buffer size: 0 vbv_delay: -1
Stream mapping:
  Stream #0:0 -> #0:0 (h264 (native) -> mpeg2video (native))
frame= 1381 fps= 16 q=14.2 size=    1950kB time=00:00:55.12 bitrate= 289.8kbits/s speed=0.657x 
```

config.json:
```sh
{
"platform": "Camera-ffmpeg",
	"cameras": [{
		"name": "pi camera",
		"videoConfig": {
			"source": "-re -i udp://192.168.0.34:8090",
			"maxStreams": 2,
			"maxWidth": 480,
			"maxHeight": 320,
			"maxFPS": 15
		}
	}]
}
```

The next step will be to reduce the stream delay, any idea?

**Comment by SphtKr** [comment]
I'm not using the camera board (yet) but I'm using a USB camera, and ffmpeg's builtin v4l2 support...I think this also works for the camera board...why not just `ffmpeg -f v4l2 -i /dev/video0`?

**Comment by cflurin** [comment]
Update:

I've installed uv4l: http://www.linux-projects.org/2016/10/25/a-new-driver-is-born/
and started the ulv4r-server (http://www.linux-projects.org/documentation/uv4l-server/)

I have no latency in any browser (mac, iPhone), that's great. Unfortunately I didn't found a reasonable solution for homebridge-camera-ffmpeg. The latency seems to be a challenge.

**Comment by yahms** [comment]
I'm also attempting using a raspberry pi cam module on the same host as homebridge, using the UV4L driver and streaming server. I couldnt get ffmpeg to grab the http stream however. Is there a trick to this, in terms of how to configure the UV4L driver, or a specific ffmpeg version? I'll admit, i was trying to use h264.

I thought I was getting somewhere by getting ffmpeg to open a h264-encoded stream from the /dev/video0 device directly, with the ' -f video4linux2 ' switch in the ffmpeg input. Didnt seem to work, as in either case the ffmpeg I was using seemed to crash straight away, and the syntax for the command sat at the homebridge console (im running homebridge direct as the logged in user)

Have started over to approach this a bit more methodically, so will post up configs and current state soon.

**Comment by cbarratt** [comment]
Currently investigating my options on this also! I was running the motioneye software and using another FFMPeg homebridge plugin, but now I'm using the "RPi Cam Web interface" which supports mjpeg and other method of streaming. 

Trying to work out how I can get the two to work together!

**Comment by GeorgViehoever** [comment]
I recently got the pi camera going on a Raspberry Pi 1 Model B (i.e. very old and slow). The camera is providing good video to Home, but not at 30 FPS - maybe 2 FPS. Anyway, the recipe outlined below should also work for more recent Raspberries and camera modules, but I did not test there. I am describing actions as taken by user pi.

- Install Raspbian Jessie (I am using the version as of June 2017)
- Install the video for Linux 2 driver with "sudo modprobe bcm2835-v4l2". After this, you should have a device called /dev/video0. Add the line "bcm2835-v4l2" with "sudo nano /etc/modules". This makes sure the driver is loaded when you reboot.
- Install node.js, homebridge and homebridge-ffmeg. Make homebridge start at boot time as user pi.
- (Compile and) Install ffmpeg with h264_omx encoder (use your favorite search engine to find recipes or precompiled packages). Note that this will require several hours of compile time. As an alternative you may be able to use avconv as describe in https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/24 , but I did not test that - the hardware supported h264_omx encoder is probably vital to get a decent performance.
- Use a ~/.homebridge/config.json file like the following:
```
...
{
  "platform": "Camera-ffmpeg",
  "cameras": [
    {
      "name": "RaspiCam",
      "uploader": false,
      "videoConfig": {
      	"source": "-re -f video4linux2 -i /dev/video0",
        "stillImageSource": "-re -f video4linux2 -ss 0.9 -i /dev/video0 -vframes 1",
       	"maxStreams": 2,
      	"maxWidth": 1280,
      	"maxHeight": 720,
      	"maxFPS": 30,
      	"vcodec": "h264_omx"            
      }
    }
  ]
}
...
```
- restart homebridge
- connect to HomeKit
- After a number of experiments the still image stopped working. Disconnecting and rebooting the iphone as described in https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/26#issuecomment-265909565 helped.
- If you are using VNC to log into your RP: This considerably slows down ffmpeg (probably because the both use the hardware encoder). Stick to ssh if this is a problem.

Enjoy,
Georg

**Comment by fabvis** [comment]
hi GeorgViehoever,
i have tried your recipe on a clean install, but i have a strange bug.
stillImage is ok in home.app, refresh every 10sec
but source streaming don't work...
and i don't have error in homebridge log
any idea ?

**Comment by GeorgViehoever** [comment]
I had just the opposite situation: Streaming worked, still images did not. The problem magically fixed itself when I did an iPhone restart as described in https://github.com/KhaosT/homebridge-camera-ffmpeg/issues/26#issuecomment-265909565 .
Only other recommendation I have: Watch the commands output by "sudo systemctl status -l -n 100 homebridge". Prefix them by "ffmpeg" and modify the end to write to a file. The worked fine for me producing readable video/image files. This led me to believe that my commands were working fine, and I went on to find issue 26.
Good luck,
Georg

**Comment by fabvis** [comment]
thanks @GeorgViehoever !
i've restart my iPad 100 times, same thing, no streaming...
strange: on another Pi (v2), same config, same jessie version, but without omx, everything is ok...

**Comment by XavM** [comment]
Thanks @GeorgViehoever !!

pi Zero w + Camera module v2 works great with ffmpeg (omx enabled build) and your conf

I had to remove from the homebridge-camera-ffmpeg code (ffmpeg.js) the resolution and scale for stillImage and videoStream to switch back to GPU encoding, and I now get a decent 10~20 FPS with pretty good video quality and 25% CPU load on the pi zero

Xavier

**Comment by Samfox2** [comment]
Yes, I had the same problems. omx only works without scaling, otherwise the streaming is very slow.

**Comment by moritzmhmk** [comment]
@Samfox2 use `-video_size WxH` instead of scaling to spare the CPU (read more [here](https://gist.github.com/moritzmhmk/48e5ed9c4baa5557422f16983900ca95))

**Comment by n0wis** [comment]
@XavM your tip works awesome, very little delay and high framerate (albeit on a rpi 3). The only issue is that the stream stops playing after about 10 seconds. Do you have the same issue?

**Comment by s-triant** [comment]
@XavM, could you explain, how you
>removed from the homebridge-camera-ffmpeg code (ffmpeg.js) the resolution and scale for stillImage and videoStream to switch back to GPU encoding

?

So far I have replaced
> -vf scale='+ width +':'+ height

with
>'

in ffmpeg.js, but the frame rate is still slow.

**Comment by moritzmhmk** [comment]
just try [homebridge-camera-rpi](https://github.com/moritzmhmk/homebridge-camera-rpi) ;)

**Comment by s-triant** [comment]
> just try homebridge-camera-rpi ;)

Much better now. Thank you!

**Comment by pcvdt** [comment]
@fabvis streaming started the moment I started using a password for the admin account in MotionEYE. Without the password Also only stills and no video. Didn’t change anything else.

**Comment by jeylites** [comment]
Hi

Will this method work on IP cameras?

Is there an alternative way to direct stream IP cameras to HomeKit without going through FFMPEG processing? 

My current device is a Raspberry Pi 3+ running independently just for cameras , and I have got 7 IP cams to it. 

The issue I have is a lag during live streaming. Despite being pixelated at times, It’s not that bad during the day but night it’s difficult to see. 

The issue remains if I have 1 or 7 cameras connected.

**Comment by tokamac** [comment]
@cflurin , @yahms :
I tried UV4L too. The MJPEG stream over HTTP is very high quality (high definition, high framerate, latency < 500 ms). Several users can watch it from various browsers at the same time. Very good solution in a browser.

But passing it through camera-ffmpeg in homebridge, I get an enormous delay in the Home app: over 7 seconds away, just as long as postmen stay. Even picking the stream directly on the pi from 127.0.0.1

What we'd need is a HTTP streaming server that can stream H.264, not MJPEG, so that we could use `-vcodec copy` instead of `libx264` or `h264_omx` (no transcoding in homebridge). I know that UV4L is advertised as being able to stream H.264 from a CSI pi-camera using their uv4L-raspicam driver, but I have an H.264 USB camera and the uv4l-uvc driver is poorly developed compared to uv4L-raspicam. BTW, forcing UV4L to use the standard uvcvideo driver with `--external-driver yes` does not work: the H.264 stream is detected but not playable in UV4L (blank screen).

Did anyone found any free HTTP or RTSP streaming server that actually streams H.264 properly?

**Comment by tokamac** [comment]
As a side note, besides UV4L, did you guys manage to open your camera stream in several Home apps on different iPhones at the same time? This is impossible for me.
