### ISSUE TITLE
It takes a long time before the stream is loaded

### ISSUE THREAD

**Issue by jobberns82** [KhaosT/homebridge-camera-ffmpeg#274]
Hi, first my apologize for my English (i'm from holland)
I had successfully installed Homebridge on my Synology Nas and i'm very happy with the ffmpeg plugin.
My Foscam camera's works both fine.  However, I have two questions.
1. It takes a long time before the stream is loaded on my iPhone.  Sometimes 30 secs. Is there a trick to get this better? with the OWLR or Foscam app I have picture after two seconds. My upload speed from my cable company is 40 Mbps. What can i do?
My config:
{
                    "name": "Woonkamer",
                    "videoConfig": {
                        "source": "-rtsp_transport tcp -re -i rtsp://jobbes:password@192.168.2.20:8220/videoMain",
                        "stillImageSource": "-i http://192.168.2.20:8220/cgi-bin/CGIProxy.fcgi?cmd=snapPicture2&usr=jobbes&pwd=password",
                        "maxStreams": 3,
                        "maxWidth": 1280,
                        "maxHeight": 720,
                        "maxFPS": 20
                    }
                }

2. How can i get also audio from my camera's in the Home app?

**Comment by tgerring** [comment]
Hello,

1. I have observed that part of the slowness to begin the video stream is in the delay launching FFMpeg as an external process. Since Homebridge is written in NodeJS, it would be faster (in theory) if NodeJS could talk to FFMpeg directly through a library. This is not a trivial fix, but certainly possible with the right developer skills in N-API. A suggestion for interested parties here: https://github.com/TruthBean/ffmpeg-nodejs

2. To the best of my knowledge, audio is not as well supported as video, so it may not be an easy fix depending on your camera and settings.

**Comment by jobberns82** [comment]
Okay, thanks for your reply
