### ISSUE TITLE
always [Camera-ffmpeg] Start streaming video from piCam with 1280x720@299kBit

### ISSUE THREAD

**Issue by lukasa1993** [KhaosT/homebridge-camera-ffmpeg#385]
cant change resolution using rpi 4 with camera module v2

```json
"platforms": [
    {
      "platform": "Camera-ffmpeg",
      "cameras": [
        {
          "name": "piCam",
          "uploader": false,
          "videoConfig": {
              "source": "-re -f video4linux2 -i /dev/video0",
              "stillImageSource": "-re -f video4linux2 -ss 0.9 -i /dev/video0 -vframes 1",
              "maxStreams": 2,
              "maxWidth": 1920,
              "maxHeight": 1080,
              "maxFPS": 30,
	      "audio": false,
              "debug": false,
	      "vcodec": "h264_omx"
          }
        }
      ]
    }
  ],

```

**Comment by shidevil** [comment]
Having the same issue as well. Always streaming with 1280x720@299kBit

**Comment by johnwest80** [comment]
I've tried multiple different options in config, and i also can't get it to use anything but 1280x720.

**Comment by eric2013264** [comment]
The resolution you set in the config file (maxWidth and maxHeight) is given to the stream controller. The stream controller determines which resolution to use. 

For example, if you pass in 1920x1080 it will push all the resolutions leading up to that to the possible resolutions list: [ 320, 240, 15 ], [ 480, 360, 30 ], [ 640, 480, 30 ], [ 640, 360, 30 ], [ 1280, 720, 30 ] (where the third number is fps). 

So that is where your config value is going. 

The stream will often start at 1280x720@299kBit because on line 258-259 in the file ffmpeg.js, in the function responsible for handling the stream "handleStreamRequest", the resolution is initialized to 1280x720 so that's reason 1. Then the code checks for a resolution in the video information of the request. The request here is the stream request received and it's Homebridge asking for a specific resolution, and it's 1280x720. And that's reason 2. I've tried upping the resolution after changing the code in this function and it works but it resulted in very choppy video.
