### ISSUE TITLE
Possible to just stream direct

### ISSUE THREAD

**Issue by ian351c** [KhaosT/homebridge-camera-ffmpeg#45]
Is it possible to add an option to just stream direct from the camera URL rather than piping through FFMPEG?

Thanks.

**Comment by KhaosT** [comment]
The way you describe is the ideal way to do HomeKit video streaming. However, since video stream is highly dependent on the physical camera and the formats it supported, it's better for people to develop optimized plugins for specific cameras to do direct streaming. This project will not try to go with this way.
