### ISSUE TITLE
Store Snapshots Locally?

### ISSUE THREAD

**Issue by thechrisreese** [KhaosT/homebridge-camera-ffmpeg#84]
Is there any way to store snapshots locally? And to use that local copy to refresh iOS?

**Comment by MrsDelish** [comment]
just use full path to you image file. 
This the line I use:
` "stillImageSource": "-i /tmp/lastsnap.jpg",`
image is generated by motion

**Comment by thechrisreese** [comment]
Ok. I am trying to figure out how that image is then sent to the Home App

**Comment by MrsDelish** [comment]
iirc, request from ios -> homebridge -> homebridge-camera-ffmpeg -> ffmpeg ->  image/mov/feed

**Comment by jannnfe** [comment]
Hello, sorry for reopen this issue.
I don't understand. I like to save the snapshot of one camera locally in my linux system.
So every time someone is ringing the bell at the door this snapshot should be saved in a folder on my system. Than I can send the Snapshot to my telegram bot, because there ist no option in iOS to view this snapshot.
Can somebody help me please?

**Comment by jannnfe** [comment]
Hello,
Thank you for your answer. there is a plugin (https://github.com/Samfox2/homebridge-videodoorbell) that supports the function of a doorbell. It behaves just like a motion detector. But that should be secondary to my question.

I would like to save exactly the image displayed as notification in ios when a motion sensor detects a motion on my Linux system, not on Google Drive. is that possible?
Thanks!

**Comment by jannnfe** [comment]
Many thanks for your response. I did not expect this to be more complex. I thought it would be very simple because that sounded so easy to me, according to @MrsDelish post:
> just use full path to you image file.
> This the line I use:
> "stillImageSource": "-i /tmp/lastsnap.jpg",
> image is generated by motion

Does he mean something else?
@ NorthernMan54 have you already rewritten your plugin to save snapshots locally?
Thanks! :)

**Comment by NorthernMan54** [comment]
In that comment they are referring to the motion module, which detects motion from a video source, and creates a file. That line then reads that file as the source for the snapshot image rather than outputting the image file there. This is the opposite of what you are asking.

For myself, I find that using google drive is easier, as I can just open drive, and look at the captured images from anywhere.
